# Site settings
title: 
header-img: img/home-bg.png
email: susanaik@gmail.com
copyright_name: Su0414
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Su0414
learn_profile: Su0414
email_username: susanaik@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
